#! /bin/sh
#
# T S T
#
# tst last edited on Fri Jun 21 23:26:28 2024 
#
# To redirect both stdout and stderr to a file, use ampersand redirect operation, for example; -
#  ./tst &> outputFile
#
EXE=webtime
TEN_PLUSS=++++++++++
#
# Test help option
echo ""
echo "${TEN_PLUSS} $EXE -h  +++help option" 
../$EXE -h
echo "${TEN_PLUSS} Shell got Return code number $? for -h options check${TEN_PLUSS}"
#
# Test Debug option
echo ""
echo "${TEN_PLUSS} $EXE -D  +++Debug option" 
../$EXE -D
echo "${TEN_PLUSS} Shell got Return code number $? for -D options check${TEN_PLUSS}"
#
